apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels" . | indent 8 }}
    spec:
      containers:
      - name: {{ .Values.deployment.mainContainer.name }}
        image: {{ .Values.deployment.mainContainer.image }}
        ports:
        - containerPort: {{ .Values.deployment.mainContainer.port }}  
        {{- if .Values.checkHealth}}{{- include "livenessProbe" . | indent 8}}{{ end }}