apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: is-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  tls:
  - hosts:
    {{- include "hosts" . | indent 4 }}
  rules:
  - host: {{ .Values.ingress.host1 }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-is
            port:
              name: {{ .Values.service.portName }}
     