---
- name: Instalar o NFS Kernel Server
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: true

- name: Criar diretório compartilhado
  file:
    path: /srv/nfs/k8s
    state: directory
    owner: nobody
    group: nogroup
    mode: "0777"

- name: Garantir entrada no /etc/exports
  lineinfile:
    path: /etc/exports
    line: "/srv/nfs/k8s 10.0.0.0/24(rw,sync,no_subtree_check,no_root_squash)"
    create: true
    state: present

- name: Aplicar exportações NFS
  command: exportfs -ra

- name: Habilitar e iniciar o serviço NFS
  systemd:
    name: nfs-server
    enabled: true
    state: started