apiVersion: v1
kind: ConfigMap
metadata:
  name: wso2-is-config
data:
  deployment.toml: |
    [server]
    hostname = "{{ .Values.config.server.hostname }}"
    node_ip = "127.0.0.1"
    base_path = "https://$ref{server.hostname}:${carbon.management.port}"

    [transport.https.properties]
    proxyPort = 443

    [super_admin]
    username = "admin"
    password = "admin"
    create_admin_account = true

    [user_store]
    type = "database_unique_id"

    [database.identity_db]
    type = "h2"
    url = "jdbc:h2:./repository/database/WSO2IDENTITY_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
    username = "wso2carbon"
    password = "wso2carbon"

    [database.shared_db]
    type = "h2"
    url = "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
    username = "wso2carbon"
    password = "wso2carbon"

    [keystore.primary]
    file_name = "wso2carbon.jks"
    password = "wso2carbon"
    type="JKS"

    [truststore]
    file_name="client-truststore.jks"
    password="wso2carbon"
    type="JKS"

    [account_recovery.endpoint.auth]
    hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

    [identity.auth_framework.endpoint]
    app_password= "dashboard"