apiVersion: v1
kind: Service
metadata:
  name: service-is
  labels:
    {{- include "labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "labels" . | indent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    name: {{ .Values.service.portName }}