---
- name: Enable TCP port 6443 (On Master) is able to connect from Worker
  wait_for: "host=k8s.lan port=6443 timeout=1"

- name: Join worker to cluster
  shell: "{{ hostvars['master1'].join_command }} --control-plane"