expose:
  type: ingress
  tls:
    enabled: false
  ingress:
    hosts:
      core: registry.patrick.dev.br
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"

externalURL: "https://registry.patrick.dev.br"
harborAdminPassword: admin