controller:
  admin:
    username: admin
    password: admin

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - docker

  serviceType: ClusterIP
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "standard" 

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
