deployment :  
  replicas : 1
  mainContainer :
    name : wso2is
    image : wso2/wso2is:latest
    port : 9443

service :
  type : NodePort
  port : 9443
  portName: https


ingress :
  host1 : dev.patrick.dev.br

checkHealth : false