- name: Install k8s
  become: yes
  hosts: tag_name_k8s
  roles:
    - k8s

- name: Setup k8s master node
  become: yes
  hosts: tag_type_master
  roles:
    - k8s-master

- name: Setup k8s worker node
  become: yes
  hosts: tag_type_worker
  roles:
    - k8s-worker

- name: Setup NFS server
  become: yes
  hosts: tag_type_worker
  roles:
    - nfsserver