- name: Setup Proxy
  hosts: proxy
  become: true
  roles:
    - docker
    - proxy

- name: Install k8s
  hosts: k8s
  become: true
  roles:
    - docker  
    - k8s

- name: Setup k8s master node
  hosts: k8s-master
  become: true
  roles:
    - k8s-master

- name: Setup k8s control-plane node
  hosts: k8s-control-plane
  become: true
  roles:
    - k8s-control-plane

- name: Setup k8s worker node
  hosts: k8s-worker
  become: true
  roles:
    - k8s-worker

- name: Setup NFS server
  become: true
  hosts: nfsserver
  roles:
    - nfs-server