- name: Install k8s
  hosts: k8s
  become: true
  roles:
    - k8s

- name: Setup k8s master node
  hosts: k8s-master
  become: true
  roles:
    - k8s-master

- name: Setup k8s worker node
  hosts: k8s-worker
  become: true
  roles:
    - k8s-worker

# - name: Setup NFS server
#   hosts: tag_type_worker
#   roles:
#     - nfsserver