- name: Destroy cluster before starting again
  command: kubeadm reset -f

- name: Initialize k8s cluster
  command: kubeadm init

- name: Install pod network
  command: kubectl apply -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Get join command
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_command