- name: Initialize k8s cluster
  command: kubeadm init --control-plane-endpoint "k8s.lan:6443" --upload-certs --pod-network-cidr=10.244.0.0/16 --service-cidr=10.245.0.0/16

- name: Upload certs e obter certificate-key
  shell: kubeadm init phase upload-certs --upload-certs | tail -n1
  register: certificate_key
  run_once: true

- name: Get join command
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_command

- name: Set Join Command
  set_fact:
    join_command: "{{ kubeadm_join_command.stdout }} --certificate-key {{ certificate_key.stdout }}"

- name: Create .kube directory
  become_user: ubuntu
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copy admin.conf to User's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu

- name: Install pod network
  command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf