---
- name: Install Docker and containerd prerequisites
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - nfs-common
    - chrony
  become: true

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

- name: Install Docker
  apt:
    name: "{{ item }}"
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
