---
- name: Disable swap
  command: swapoff -a
  become: true

- name: Ensure swap is disabled in fstab
  lineinfile:
    path: /etc/fstab
    regexp: "^.*swap.*$"
    state: absent
  become: true

- name: Load necessary kernel modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
      nf_nat
      xt_REDIRECT
      xt_owner
      iptable_nat
      iptable_mangle
      iptable_filter
    owner: root
    group: root
    mode: '0644'

- name: Load kernel modules to K8S/Containerd
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter
    - nf_nat
    - xt_REDIRECT
    - xt_owner
    - iptable_nat
    - iptable_mangle
    - iptable_filter

- name: Apply sysctl settings
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward

- name: Reload sysctl settings
  command: sysctl --system
  become: true
