---
- name: Create config directory
  file:
    path: /opt/proxy/etc-nginx
    state: directory

- name: Copy Nginx config
  copy:
    src: files/nginx.conf
    dest: /opt/proxy/etc-nginx/nginx.conf
    mode: '0644'

- name: Create config directory
  file:
    path: /opt/proxy/etc-pihole
    state: directory

- name: Copiar pihole.docker-compose.yml
  copy:
    src: files/docker-compose.yml
    dest: "/opt/proxy/docker-compose.yml"
    mode: '0644'

- name: Subir serviços com docker-compose
  community.docker.docker_compose_v2:
    project_src: "/opt/proxy"
    state: present

- name: Esperar arquivo pihole.toml existir
  wait_for:
    path: "/opt/proxy/etc-pihole/pihole.toml"
    state: present
    timeout: 60

- name: Parar o container Docker
  docker_container:
    name: pihole
    state: stopped

- name: Inserir bloco de hosts no pihole.toml
  replace:
    path: /opt/proxy/etc-pihole/pihole.toml
    regexp: 'hosts\s*=\s*\[\s*(?:.|\n)*?\s*]'
    replace: 'hosts = ["10.0.0.10 pihole.lan", "10.0.0.1 modem.lan", "10.0.0.10 k8s.lan"]'

- name: Parar o container Docker
  docker_container:
    name: pihole
    state: started